---
# 1. [Init] 로컬 SSD에 서비스 담을 폴더 생성
- name: Ensure Local Service Directory exists
  file:
    path: "{{ local_service_path }}/{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop: "{{ target_services }}"



# [수정 후: 확실한 방법 (rsync 직접 호출)]
- name: Stat Source Service Directory
  stat:
    path: "{{ client_mount_path }}/{{ item }}/"
  register: source_dir_stats
  loop: "{{ target_services }}"

- name: Stat Local Service Directory
  stat:
    path: "{{ local_service_path }}/{{ item }}/"
  register: dest_dir_stats
  loop: "{{ target_services }}"

- name: Full Sync from NFS to Local (Skip if target newer)
  command: "rsync -a {{ client_mount_path }}/{{ item }}/ {{ local_service_path }}/{{ item }}/"
  loop: "{{ target_services }}"
  loop_control:
    index_var: svc_index
  when:
    - source_dir_stats.results[svc_index].stat.exists
    - dest_dir_stats.results[svc_index].stat.exists
    - source_dir_stats.results[svc_index].stat.mtime > dest_dir_stats.results[svc_index].stat.mtime
