---
- name: "노드 환경 미화 (Cleanup)"
  hosts: tmp_nodes  
  become: yes
  tasks:
    - name: "기존 쓰레기 폴더 삭제"
      file:
        path: "/home/{{ ansible_user }}/docker_volumes/{{ item }}"
        state: absent
      loop:
        - nginx-proxy-manager
        - home-assistant
        - ghost
        - homepage
        - authentik
        - code-server
        - uptimekuma
        - grafana
        - wireguard
